### ISSUE TITLE
How do I convert to CSS?

### ISSUE THREAD

**Issue by graingerkid** [Wikiki/bulma-pricingtable#3]
Hi, 

I'm a bit confused about how to turn this into CSS?

Could you point me in the right direction?

**Comment by Wikiki** [comment]
Hi,

you have to follow the guide here: https://wikiki.github.io/bulma-extensions/overview
You can't user it alone. It has to be integrated into Bulma.

Regards

**Comment by betososa** [comment]
Hi, that link is broken, this is the link that helped me, in case someone needs it
https://wikiki.github.io/#getting-started

Thanks!
