### ISSUE TITLE
Control which plan item goes on top?

### ISSUE THREAD

**Issue by exwizzard** [Wikiki/bulma-pricingtable#6]
Hello,

When I have 3 plan-items and view the page in a mobile view the first 2 will go side by side and the third one will be below and full size.

Is it possible to control which plan-item will be full sized? For example I want the first plan-item to be full size while the second and third will be below and next to each other.

Example:

![image](https://user-images.githubusercontent.com/1271688/34876607-9ea422d0-f7a2-11e7-98ca-32c94aa43537.png)

**Comment by exwizzard** [comment]
Sorry I meant pricing-plan not plan-item.

**Comment by Wikiki** [comment]
Can you please provide a codepen http://codepen.io) in order for me to test ?
Because on my side each plan-item take full-width

**Comment by Wikiki** [comment]
Hi @exwizzard,

you can try the new <code>is-plan-first-mobile</code> modifier.

regards
