### ISSUE TITLE
Version 1.0.0 is broken due to @import in sass file

### ISSUE THREAD

**Issue by jmfederico** [Wikiki/bulma-pricingtable#8]
When using version 1.0.0 of this extension with Webpack I was getting the following error:

```
      File to import not found or unreadable: initial-variables.sass.
      in /my/path/node_modules/bulma-pricingtable/dist/bulma-pricingtable.sass (line 3, column 1)
```

I then downgraded to version 0.1.10 and it worked.

The diff between the 2 versions for the dist sass file is:

```diff
diff --unified -r bulma-pricingtable-0.1.10/dist/bulma-pricingtable.sass bulma-pricingtable-1.0.0/dist/bulma-pricingtable.sass
--- bulma-pricingtable-0.1.10/dist/bulma-pricingtable.sass	2018-02-10 03:59:52.000000000 -0500
+++ bulma-pricingtable-1.0.0/dist/bulma-pricingtable.sass	2018-02-10 11:40:06.000000000 -0500
@@ -1,3 +1,12 @@
+@charset "utf-8"
+
+@import "initial-variables.sass"
+@import "functions.sass"
+@import "derived-variables.sass"
+@import "animations.sass"
+@import "mixins.sass"
+@import "controls.sass"
+
 $pricing-plan-border: .1rem solid $white-ter !default
 $pricing-plan-border-radius: $radius !default
 $pricing-plan-active-shadow: 0 8px 12px 0 rgba($grey, 0.2) !default
```

I take that those `@import` are broken, they have a path which will never work.

**Comment by SimplyThomas** [comment]
This looks like a bug with the gulp build process. I'm not familiar enough with gulp to help debug it, but it does look like it's not keeping the full bulma path during the build process. 

@Wikiki  will have to poke around some to fix it.

**Comment by SimplyThomas** [comment]
@jmfederico you can temporarily fix by fixing the import manually until a fix gets pushed

@import "~bulma/sass/utilities/all"

**Comment by jmfederico** [comment]
I downgraded to version 0.1.10 which provides the same styles and it works. 👍

**Comment by Wikiki** [comment]
Hi,

please update to version 1.2.0
